package protocol

const (
	FieldAppID         = "app_id"
	FieldOrderNo       = "order_no"
	FieldOutOrderNo    = "out_order_no"
	FieldAmount        = "amount"
	FieldTitle         = "title"
	FieldPayType       = "pay_type"
	FieldOpenID        = "openid"
	FieldReturnURL     = "return_url"
	FieldNotifyURL     = "notify_url"
	FieldExtra         = "extra"
	FieldRefundNo      = "refund_no"
	FieldReason        = "reason"
	FieldStatus        = "status"
	FieldTransactionID = "transaction_id"
	FieldPaidAt        = "paid_at"
	FieldTimestamp     = "timestamp"
	FieldNonce         = "nonce"
	FieldSign          = "sign"
	FieldData          = "data"
	FieldAppSecret     = "app_secret"
	FieldSuccessTime   = "success_time"
	FieldRefundAmount  = "refund_amount"
	FieldRefundReason  = "refund_reason"
	FieldCreatedAt     = "created_at"
	FieldOrderAmount   = "order_amount"
	FieldTotalRefunded = "total_refunded"
	FieldRemaining     = "remaining_amount"
	FieldCanRefund     = "can_refund"
	FieldMessage       = "message"
	FieldCode          = "code"
	FieldPayURL        = "pay_url"
	FieldCodeURL       = "code_url"
	FieldError         = "error"
	FieldContentType   = "Content-Type"
)
