server:
  port: "8081"

payment:
  app_id: "app_d25ccc24bbef8b9c"
  app_secret: "5f0a5802710951fe52665469b1eb31ab"
  base_url: "https://pay.xgdn.net"
  public_url: "https://shop-demo.xgdn.net"

jwt:
  secret: "your-secure-jwt-secret-key"

database:
  path: "./shop-demo.db"
